name: status check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: sleep 20
      - name: Runs on failure
        if: failure()
        run: echo "runs on failure"
      - name: runs on success
        if: success()
        run: echo "runs on success"

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps: 
      - run: echo 'Job2'
